services:
    api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
       - GIN_MODE=release
      entrypoint: ["/app/start.sh"]
      command: ["/app/main"]
