name: Deploy to server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add secrets to start.sh
        run: |
          sed -i '8i\echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> "/app/app.env"\n' start.sh
          sed -i '9i\echo "OPENAI_TOKEN=${{ secrets.OPENAI_TOKEN }}" >> "/app/app.env"\n' start.sh

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t aspandyar/aspandyar_bot:latest .

      - name: Push Docker image to Docker Hub
        run: docker push aspandyar/aspandyar_bot:latest

      - name: Clear Docker images and containers on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/aspandyar
            docker ps -aq --filter "name=aspandyar_bot" | grep -q . && docker stop aspandyar_bot && docker rm aspandyar_bot || echo "No running container to remove"
            docker images -q aspandyar/aspandyar_bot:latest | grep -q . && docker rmi -f aspandyar/aspandyar_bot:latest || echo "No image to remove"

      - name: SSH to Server and Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}  
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/aspandyar
            docker pull aspandyar/aspandyar_bot:latest
            docker run -d --name aspandyar_bot -p 8080:8080 aspandyar/aspandyar_bot:latest
